# Product catalog for e-commerce application

# Define product categories
categories = ["Electronics", "Wearables", "Audio", "Accessories", "Office", "Travel"]

products = [
    {
        "id": 1,
        "name": "Smart Watch Pro",
        "price": 129.99,
        "original_price": 159.99,
        "description": "Track your fitness and stay connected with notifications. Features include heart rate monitoring, sleep tracking, and water resistance.",
        "image": "https://placehold.co/600x400?text=Smart+Watch+Pro",
        "thumbnail": "https://placehold.co/100x100?text=Watch",
        "category": "Wearables",
        "rating": 4.5,
        "reviews": 128,
        "in_stock": True,
        "features": [
            "Heart Rate Monitor",
            "Sleep Tracking",
            "Water Resistant",
            "Notification Alerts",
        ],
    },
    {
        "id": 2,
        "name": "Premium Wireless Earbuds",
        "price": 89.99,
        "original_price": 109.99,
        "description": "Immersive sound with active noise cancellation. Enjoy crystal clear audio with 8 hours of battery life and wireless charging case.",
        "image": "https://placehold.co/600x400?text=Premium+Wireless+Earbuds",
        "thumbnail": "https://placehold.co/100x100?text=Earbuds",
        "category": "Audio",
        "rating": 4.7,
        "reviews": 245,
        "in_stock": True,
        "features": [
            "Active Noise Cancellation",
            "Wireless Charging",
            "8hr Battery Life",
            "Water Resistant",
        ],
    },
    {
        "id": 3,
        "name": "Portable Bluetooth Speaker",
        "price": 59.99,
        "original_price": 79.99,
        "description": "Waterproof speaker with 12-hour battery life. Perfect for outdoor adventures with powerful bass and 360° sound.",
        "image": "https://placehold.co/600x400?text=Portable+Bluetooth+Speaker",
        "thumbnail": "https://placehold.co/100x100?text=Speaker",
        "category": "Audio",
        "rating": 4.3,
        "reviews": 92,
        "in_stock": True,
        "features": ["Waterproof", "12hr Battery", "Bluetooth 5.0", "360° Sound"],
    },
    {
        "id": 4,
        "name": "Professional Laptop Backpack",
        "price": 49.99,
        "original_price": 69.99,
        "description": 'Padded backpack with multiple compartments for laptops up to 15.6". Includes anti-theft pockets and USB charging port.',
        "image": "https://placehold.co/600x400?text=Professional+Laptop+Backpack",
        "thumbnail": "https://placehold.co/100x100?text=Backpack",
        "category": "Travel",
        "rating": 4.6,
        "reviews": 187,
        "in_stock": True,
        "features": [
            "Anti-theft Design",
            "USB Charging Port",
            "Water Resistant",
            "Multiple Compartments",
        ],
    },
    {
        "id": 5,
        "name": "Adjustable Phone Stand",
        "price": 19.99,
        "original_price": 24.99,
        "description": "Adjustable stand compatible with all smartphones. Perfect for video calls, watching movies, or following recipes.",
        "image": "https://placehold.co/600x400?text=Adjustable+Phone+Stand",
        "thumbnail": "https://placehold.co/100x100?text=Stand",
        "category": "Accessories",
        "rating": 4.2,
        "reviews": 64,
        "in_stock": True,
        "features": [
            "Adjustable Angle",
            "Anti-Slip Base",
            "Foldable",
            "Universal Compatibility",
        ],
    },
    {
        "id": 6,
        "name": "USB-C Hub Multiport Adapter",
        "price": 39.99,
        "original_price": 49.99,
        "description": "7-in-1 hub with HDMI, USB ports, and card readers. Connect multiple devices to your laptop with this sleek aluminum adapter.",
        "image": "https://placehold.co/600x400?text=USB-C+Hub+Multiport+Adapter",
        "thumbnail": "https://placehold.co/100x100?text=USB+Hub",
        "category": "Electronics",
        "rating": 4.4,
        "reviews": 156,
        "in_stock": True,
        "features": ["HDMI Output", "3 USB Ports", "SD Card Reader", "Power Delivery"],
    },
    {
        "id": 7,
        "name": "Wireless Charging Pad",
        "price": 29.99,
        "original_price": 39.99,
        "description": "Fast wireless charging for all Qi-enabled devices. Sleek, minimal design with LED indicator and anti-slip surface.",
        "image": "https://placehold.co/600x400?text=Wireless+Charging+Pad",
        "thumbnail": "https://placehold.co/100x100?text=Charger",
        "category": "Electronics",
        "rating": 4.1,
        "reviews": 73,
        "in_stock": True,
        "features": [
            "Fast Charging",
            "Qi Compatible",
            "LED Indicator",
            "Anti-Slip Surface",
        ],
    },
    {
        "id": 8,
        "name": "Noise Cancelling Headphones",
        "price": 149.99,
        "original_price": 199.99,
        "description": "Over-ear headphones with advanced noise cancellation technology. Enjoy immersive audio with 30 hours of battery life.",
        "image": "https://placehold.co/600x400?text=Noise+Cancelling+Headphones",
        "thumbnail": "https://placehold.co/100x100?text=Headphones",
        "category": "Audio",
        "rating": 4.8,
        "reviews": 342,
        "in_stock": True,
        "features": [
            "Active Noise Cancellation",
            "30hr Battery",
            "Bluetooth 5.0",
            "Comfortable Design",
        ],
    },
]
